In [2]:
import numpy as np
import pandas as pd

from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
from sklearn.model_selection import GridSearchCV

In [4]:
df = pd.read_csv("heart_failure_clinical_records_dataset.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT               299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.5 KB


In [6]:
x=df.iloc[:, :-1].values
y=df.iloc[:, 1].values

In [7]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size= 0.2, random_state=150)

In [8]:
knn_model= KNeighborsClassifier()

In [9]:
params = {
    #'n_neighbors' : [3, 5, 7, 9, 11, 13],
   # 'metric' : ['cosine', 'euclidean', 'manhattan'],
    #'weights': ['uniform', 'distance']
    'C' : [0,1,1,10,100],
    'gamma': [1, 0, 1, 1, 0.01, 0.001],
    'kernel' : ['rbf', 'linear']
}

In [10]:
gridsearch = GridSearchCV(
    SVC(),
    params,
    verbose=1, #progressbar dekhaune
    cv=2, #cross validation
   # n_jobs = -1
)

In [11]:
gridsearch_result=gridsearch.fit(train_x, train_y)

Fitting 2 folds for each of 60 candidates, totalling 120 fits


In [ ]:
gridsearch_result.best_score_ 

0.6023734177215189

In [ ]:
gridsearch_result.best_estimator_

KNeighborsClassifier(metric='cosine', n_neighbors=9)

In [ ]:
gridsearch_result.best_params_

{'metric': 'cosine', 'n_neighbors': 9, 'weights': 'uniform'}

In [ ]:
knn_model= KNeighborsClassifier(metric='cosine', n_neighbors = 7, weights= 'uniform') 

In [ ]:
knn_model.fit(train_x, train_y)


KNeighborsClassifier(metric='cosine', n_neighbors=7)

In [ ]:
y_pred=knn_model.predict(test_x)

In [ ]:
y_pred


array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       0.68      0.68      0.68        34
           1       0.58      0.58      0.58        26

    accuracy                           0.63        60
   macro avg       0.63      0.63      0.63        60
weighted avg       0.63      0.63      0.63        60



In [ ]:
pred = svc_model.predict(test_x)

In [ ]:
pred


array([0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0])

In [ ]:
print(classification_report(test_y, pred))

              precision    recall  f1-score   support

           0       0.60      0.71      0.65        34
           1       0.50      0.38      0.43        26

    accuracy                           0.57        60
   macro avg       0.55      0.55      0.54        60
weighted avg       0.56      0.57      0.56        60



In [ ]:
confusion_matrix(test_y, pred)

array([[24, 10],
       [16, 10]])